/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as FidelityRouteImport } from './routes/fidelity'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as SnakeRouteImport } from './routes/snake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelityRoute = FidelityRouteImport.update({
  id: '/fidelity',
  path: '/fidelity',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakeRoute = SnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/convert': typeof ConvertRoute
  '/fidelity': typeof FidelityRoute
  '/playground': typeof PlaygroundRoute
  '/snake': typeof SnakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/convert': typeof ConvertRoute
  '/fidelity': typeof FidelityRoute
  '/playground': typeof PlaygroundRoute
  '/snake': typeof SnakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/convert': typeof ConvertRoute
  '/fidelity': typeof FidelityRoute
  '/playground': typeof PlaygroundRoute
  '/snake': typeof SnakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/benchmarks' | '/convert' | '/fidelity' | '/playground' | '/snake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmarks' | '/convert' | '/fidelity' | '/playground' | '/snake'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/convert'
    | '/fidelity'
    | '/playground'
    | '/snake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  ConvertRoute: typeof ConvertRoute
  FidelityRoute: typeof FidelityRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SnakeRoute: typeof SnakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelity': {
      id: '/fidelity'
      path: '/fidelity'
      fullPath: '/fidelity'
      preLoaderRoute: typeof FidelityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  ConvertRoute: ConvertRoute,
  FidelityRoute: FidelityRoute,
  PlaygroundRoute: PlaygroundRoute,
  SnakeRoute: SnakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
